/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as FooContractJson } from "../Foo.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace FooTypes {
  export type Fields = {
    owner: Address;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    destroy: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    destroy: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<FooInstance, FooTypes.Fields> {
  encodeFields(fields: FooTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as FooTypes.Fields;
  }

  consts = { ErrorCodes: { NotOwner: BigInt(0) } };

  at(address: string): FooInstance {
    return new FooInstance(address);
  }

  tests = {
    destroy: async (
      params: Omit<
        TestContractParamsWithoutMaps<FooTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "destroy", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const Foo = new Factory(
  Contract.fromJson(
    FooContractJson,
    "",
    "ab6dbe32a68a1207a83b6f2494e3d576cdc70fa6d3282b9f569977f12b49e577",
    []
  )
);

// Use this class to interact with the blockchain
export class FooInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FooTypes.State> {
    return fetchContractState(Foo, this);
  }

  methods = {
    destroy: async (
      params?: FooTypes.CallMethodParams<"destroy">
    ): Promise<FooTypes.CallMethodResult<"destroy">> => {
      return callMethod(
        Foo,
        this,
        "destroy",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  view = this.methods;

  transact = {
    destroy: async (
      params: FooTypes.SignExecuteMethodParams<"destroy">
    ): Promise<FooTypes.SignExecuteMethodResult<"destroy">> => {
      return signExecuteMethod(Foo, this, "destroy", params);
    },
  };
}
